version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    environment:
      - BOT_TOKEN
      - DATABASE_URL
      - FEEDBACK_CHAT_ID
      - SUPPORT_CHAT_ID
      - ADMIN_IDS
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
