[tool.black]
line-length = 88
target-version = ["py311"]
skip-string-normalization = false
skip-magic-trailing-comma = false

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["app"]
