"""add_appeals

Revision ID: a58550d61f42
Revises: de778fb1a252
Create Date: 2025-07-28 20:39:36.847916

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a58550d61f42"
down_revision: Union[str, Sequence[str], None] = "de778fb1a252"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appeals_statistics",
        sa.Column("time", sa.String(), nullable=False),
        sa.Column("counter", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("time"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("appeals_statistics")
    # ### end Alembic commands ###
