"""add_statistics

Revision ID: de778fb1a252
Revises: a2e9c49d0429
Create Date: 2025-07-23 17:52:50.373207

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de778fb1a252"
down_revision: Union[str, Sequence[str], None] = "a2e9c49d0429"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "FAQ_statistics",
        sa.Column("time", sa.String(), nullable=False),
        sa.Column("counter", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("time"),
    )
    op.create_table(
        "broadcast_statistics",
        sa.Column("time", sa.String(), nullable=False),
        sa.Column("counter", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("time"),
    )
    op.create_table(
        "feedback_statistics",
        sa.Column("time", sa.String(), nullable=False),
        sa.Column("counter", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("time"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback_statistics")
    op.drop_table("broadcast_statistics")
    op.drop_table("FAQ_statistics")
    # ### end Alembic commands ###
